/** Build fully rendered HTML from plain JSON. No browser-side content fetching,
 * framework runtime, package installation, or external APIs are required. */
import {readFile, writeFile, mkdir} from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const read=async name=>JSON.parse(await readFile(path.join(root,'content',name+'.json'),'utf8'));
const [site,team,projects,pubs,funding,source]=await Promise.all(['site','team','projects','publications','funding','source-snapshot'].map(read));
// Content is treated as text, never executable HTML.
const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const slug=value=>value.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const paragraphs=items=>items.map(t=>`<p>${e(t)}</p>`).join('');
const arrow='<span aria-hidden="true">↗</span>';
// Lucide-style stroke icons; see THIRD_PARTY_NOTICES.md.
const icons={github:'<path d="M9 19c-5 1.5-5-2.5-7-3m14 6v-3.87a3.37 3.37 0 0 0-.94-2.61c3.14-.35 6.44-1.54 6.44-7A5.44 5.44 0 0 0 20 4.77 5.07 5.07 0 0 0 19.91 1S18.73.65 16 2.48a13.38 13.38 0 0 0-7 0C6.27.65 5.09 1 5.09 1A5.07 5.07 0 0 0 5 4.77a5.44 5.44 0 0 0-1.5 3.78c0 5.42 3.3 6.61 6.44 7A3.37 3.37 0 0 0 9 18.13V22"/>',instagram:'<rect width="20" height="20" x="2" y="2" rx="5"/><circle cx="12" cy="12" r="4"/><path d="M17.5 6.5h.01"/>'};
const icon=name=>`<svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icons[name]}</svg>`;
const nav=[['','Home'],['about-us','About Us'],['team','Team'],['projects','Projects'],['publications','Publications'],['contact','Contact Us']];
const a=(href,text,cls='')=>`<a class="${cls}" href="${e(href)}">${text}</a>`;
const img=(file,alt,cls='')=>`<img class="${cls}" src="/assets/${e(file)}" alt="${e(alt)}" loading="lazy" decoding="async">`;
function shell(route,title,desc,body){return `<!doctype html>
<html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${e(title)} | IMASS</title><meta name="description" content="${e(desc)}"><link rel="canonical" href="${e(site.url)}/${route?route+'/':''}"><meta property="og:title" content="${e(title)} | IMASS"><meta property="og:description" content="${e(desc)}"><meta property="og:type" content="website"><meta property="og:url" content="${e(site.url)}/${route?route+'/':''}"><meta name="theme-color" content="#123f45"><link rel="icon" href="/assets/pfp.png"><link rel="stylesheet" href="/assets/styles.css"><script defer src="/assets/main.js"></script></head>
<body><a class="skip" href="#main">Skip to content</a><div class="institution"><div class="wrap">${e(site.eyebrow)}<span>Institute for Minimal Access Surgical Sciences</span></div></div>
<header class="header"><div class="wrap nav-wrap"><a class="brand" href="/" aria-label="IMASS home"><img src="/assets/pfp.png" width="250" height="76" alt="IMASS — Institute for Minimal Access Surgical Sciences"></a><button class="menu-button" aria-expanded="false" aria-controls="navigation" hidden>Menu <span aria-hidden="true">☰</span></button><nav id="navigation" aria-label="Main navigation">${nav.map(([r,t])=>`<a href="/${r?r+'/':''}" ${r===route?'aria-current="page"':''}>${t}</a>`).join('')}</nav></div></header>
<main id="main">${body}</main>
<footer><div class="wrap footer-top"><div><p class="footer-mark">IMASS<span>Research. Education. Surgical care.</span></p><p class="footer-name">${e(site.name)}</p><p>University of Manitoba<br>Winnipeg, Canada</p></div><div><h2>Explore</h2><div class="footer-nav">${nav.slice(1).map(([r,t])=>a('/'+r+'/',e(t))).join('')}</div></div><div><h2>Connect with IMASS</h2>${a('mailto:'+site.email,e(site.email))}<div class="socials">${a(site.github,icon('github')+'GitHub')}${a(site.instagram,icon('instagram')+'Instagram')}</div></div></div><div class="wrap footer-bottom"><span>© ${new Date().getUTCFullYear()} ${e(site.name)}</span><span>St. Boniface General Hospital · Winnipeg</span></div></footer></body></html>`;}
const heading=(label,title,desc)=>`<section class="page-heading"><div class="wrap"><p class="eyebrow">${e(label)}</p><h1>${e(title)}</h1><p class="lede">${e(desc)}</p></div></section>`;
const areaCards=()=>`<div class="area-grid">${site.researchAreas.map((p,i)=>`<a class="area" href="/projects/#${e(p.anchor)}"><span class="number">0${i+1}</span><h3>${e(p.title)}</h3><p>${e(p.text)}</p><span class="text-link">Explore research ${arrow}</span></a>`).join('')}</div>`;
const projectCard=p=>`<article class="project-card">${p.images.length?`<div class="project-images">${p.images.map(f=>a('/assets/'+f,img(f,p.title),'image-link')).join('')}</div>`:''}<div class="project-copy"><p class="eyebrow">${e(p.category)}</p><h3>${e(p.title)}</h3>${p.description?paragraphs([p.description]):''}</div></article>`;
const home=`<section class="hero"><div class="hero-copy"><p class="eyebrow">Institute for Minimal Access Surgical Sciences</p><h1>${e(site.headline).replace('\n','<br>')}</h1><p>${e(site.intro)}</p><div class="actions">${a('/projects/','Explore our research '+arrow,'button')}${a('/about-us/','About IMASS','quiet-link')}</div><div class="hero-location">Department of Surgery<br><strong>St. Boniface General Hospital</strong></div></div><div class="hero-photo"><img src="/assets/cover.jpg" alt="Laparoscopic instruments in use during minimally invasive surgery" width="800" height="400" fetchpriority="high"><div class="photo-caption"><span>Precision in practice.</span><span>Progress through discovery.</span></div></div></section>
<section class="section wrap"><div class="section-head"><div><p class="eyebrow">Our research</p><h2>Better care starts<br>with better questions.</h2></div><p>From clinical outcomes to the skills that underpin safe surgery, our work connects evidence, education, and patient experience.</p></div>${areaCards()}</section>
<section class="tinted"><div class="section wrap"><div class="section-head"><div><p class="eyebrow">In the lab</p><h2>Understanding how surgeons learn.</h2></div>${a('/projects/','All projects '+arrow,'text-link')}</div><div class="project-grid">${projects.filter(p=>p.images.length).map(projectCard).join('')}</div></div></section>
<section class="section wrap team-invite"><div><p class="eyebrow">The people behind the research</p><h2>Clinical insight.<br>Shared curiosity.</h2><p>Meet the surgeons, researchers, and students contributing to IMASS.</p>${a('/team/','Meet our team '+arrow,'button')}</div><div class="portrait-strip">${team.filter(m=>m.image).map(m=>a('/team/#'+slug(m.name),img(m.image,m.name)+`<span>${e(m.name)}</span>`)).join('')}</div></section>`;
const about=heading('About IMASS','Research with a purpose.','Advancing patient care and surgical proficiency in Winnipeg, Manitoba.')+`<section class="section wrap article-layout"><aside><p class="eyebrow">Who we are</p><p>General Surgery Research Team<br>St. Boniface General Hospital<br>University of Manitoba</p>${a('/team/','Meet the team '+arrow,'text-link')}</aside><div class="prose">${source['about-us'].filter(b=>b.tag==='p'&&!b.text.includes('Research Focus')).map(b=>`<p class="lead-paragraph">${e(b.text)}</p>`).join('')}<h2>Our research focus</h2>${source['about-us'].filter(b=>b.tag==='li').map(b=>{const i=b.text.indexOf(':');return `<h3>${e(b.text.slice(0,i))}</h3><p>${e(b.text.slice(i+1).trim())}</p>`}).join('')}</div></section>`;
const groups=[...new Set(team.map(m=>m.group))];
const member=m=>`<article class="member ${m.image?'with-photo':''}" id="${slug(m.name)}">${m.image?img(m.image,m.name,'portrait'):''}<div class="member-body"><h3>${e(m.name)}</h3><p class="role">${e(m.role)}</p>${m.dates?`<p class="dates">${e(m.dates)}</p>`:''}${m.bio.length?`<details><summary>Read biography <span aria-hidden="true">+</span></summary><div class="bio">${paragraphs(m.bio)}</div></details>`:''}</div></article>`;
const teamPage=heading('Our team','People make progress.','Meet the IMASS research team and the students who have contributed to our work.')+`<div class="wrap jump-links" aria-label="Team sections">${groups.map(g=>a('#'+slug(g),e(g))).join('')}</div><div class="wrap">${groups.map(g=>`<section class="section team-section" id="${slug(g)}"><h2>${e(g)}</h2><div class="member-grid ${g==='Previous members'?'alumni-grid':''}">${team.filter(m=>m.group===g).map(member).join('')}</div></section>`).join('')}</div>`;
const categories=[...new Set(projects.map(p=>p.category))];
const projectPage=heading('Our projects','Questions that move surgery forward.','Clinical trials, surgical simulation, community collaboration, and surgical outcomes research.')+`<div class="wrap jump-links">${categories.map(c=>a('#'+slug(c),e(c))).join('')}${a('#funding','Funding support')}</div><div class="wrap">${categories.map(c=>`<section class="section" id="${slug(c)}"><h2>${e(c)}</h2><div class="project-grid ${c==='Surgical Simulation'?'':'text-projects'}">${projects.filter(p=>p.category===c).map(projectCard).join('')}</div></section>`).join('')}<section class="section funding" id="funding"><h2>Funding support</h2><p class="muted">Funding awards recorded by IMASS.</p><details><summary>View funding record <span>${funding.length} awards</span></summary><ul>${funding.map(f=>`<li>${e(f)}</li>`).join('')}</ul></details></section></div>`;
const publicationPage=heading('Publications','Evidence, shared.','Explore the IMASS publication record across clinical care, surgical education, and simulation.')+`<section class="section wrap"><div class="publication-tools" hidden><label>Search publications<input id="publication-search" type="search" placeholder="Title, author, journal, or keyword"></label><label>Publication year<select id="publication-year"><option value="">All years</option>${[...new Set(pubs.map(p=>p.year).filter(Boolean))].sort((a,b)=>b-a).map(y=>`<option>${y}</option>`).join('')}</select></label><button id="reset-filters" class="filter-reset" type="button">Reset</button></div><p id="publication-count" role="status" aria-live="polite">${pubs.length} publications</p><ol class="publications">${pubs.map(p=>`<li data-publication data-year="${p.year||''}"><span class="pub-year">${p.year||'In press'}</span><div><p>${e(p.citation)}</p>${p.url?a(p.url,'View publication '+arrow,'text-link'):''}</div></li>`).join('')}</ol><p id="no-results" hidden>No publications match these filters. Try another keyword or reset the filters.</p></section>`;
const contact=heading('Contact us','Let’s connect.','Get in touch with the IMASS research team.')+`<section class="section wrap contact-grid"><div class="contact-primary"><p class="eyebrow">Email the lab</p>${a('mailto:'+site.email,e(site.email),'contact-email')}<p>For questions about our research and projects.</p><div class="socials">${a(site.github,icon('github')+'GitHub')}${a(site.instagram,icon('instagram')+'Instagram')}</div></div><div class="contact-address"><h2>Find us</h2><address>${site.address.map(e).join('<br>')}</address><h3>Telephone</h3>${a('tel:'+site.phoneLink,e(site.phone))}</div></section>`;
const pages=[['','Home',site.description,home],['about-us','About Us','About the IMASS General Surgery Research Team.',about],['team','Team','Meet the IMASS faculty, researchers, students, and previous members.',teamPage],['projects','Projects','Explore IMASS projects and funding support.',projectPage],['publications','Publications','The IMASS research publication record.',publicationPage],['contact','Contact Us','Contact IMASS in Winnipeg, Manitoba.',contact]];
for(const [route,title,desc,body] of pages){const dir=path.join(root,'dist',route);await mkdir(dir,{recursive:true});await writeFile(path.join(dir,'index.html'),shell(route,title,desc,body));}
await writeFile(path.join(root,'dist/404.html'),shell('404','Page not found','This page could not be found.',heading('404','This page isn’t here.','The link may have changed.')+'<div class="section wrap">'+a('/','Return to IMASS home','button')+'</div>'));
await writeFile(path.join(root,'dist/.nojekyll'),'');
await writeFile(path.join(root,'dist/robots.txt'),`User-agent: *\nAllow: /\nSitemap: ${site.url}/sitemap.xml\n`);
await writeFile(path.join(root,'dist/sitemap.xml'),`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${pages.map(([r])=>`<url><loc>${e(site.url)}/${r?r+'/':''}</loc></url>`).join('')}</urlset>`);
console.log(`Built ${pages.length} pages, ${team.length} people, ${projects.length} projects, ${pubs.length} publication entries.`);
